application: blog-homework
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# add folders to be available
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js
  
- url: /.*
  script: myBlog.app
  
libraries:
- name: jinja2
  version: latest